# Conclusion

Overall, we have established that COVID-19 impacted education in several significant ways, both directly and indirectly. Through the various plots, we were able to see that the amount of money spent on education and the country’s overall economic performance (measured in GDP per capita) were somewhat of an indicator as to whether the country’s PISA scores were high or not. Moreover, we saw trends in overall student well-being by comparing the data from 2018 to 2022. There were obvious decreases there, hence suggesting that COVID might have been a reason. This is further proven by the linked articles about society and education during that tumultuous time. Some limitations in our analysis were that we did not have similar “percentage of burnt out students” data for other countries, which would have been an interesting thing to investigate. Perhaps we could also further our investigation by looking into more 3rd world countries. However, many of those countries have not taken the PISA, which is something that we cannot control or supplement with other scores. We could definitely look into other metrics (such as the SAT) and see whether that changes our conclusions.
